### ISSUE TITLE
Add FDR threshold to manhattan plot

### ISSUE THREAD

**Issue by nep63** [HallLab/clarite-python#22]
For the manhattan plots if we can add a manual input option to have it only show the threshold for FDR instead of only Bonferroni will be can be useful for future analysis.

**Comment by jrm5100** [comment]
Added "bonferroni" and "fdr" parameters to the manhattan plot function.

Either can be *None* (to not draw a line) or a float value, meaning there are 4 possibilities:

No lines:

![neither](https://user-images.githubusercontent.com/2191259/70184929-da447580-16b6-11ea-8a68-37fe53a117d9.png)

Both lines:

![both](https://user-images.githubusercontent.com/2191259/70184925-da447580-16b6-11ea-9aea-5c3d624fb86d.png)

Bonferroni only (default):

![bonferroni](https://user-images.githubusercontent.com/2191259/70184924-da447580-16b6-11ea-9057-628b2e3e43ff.png)


FDR only:

![fdr](https://user-images.githubusercontent.com/2191259/70184927-da447580-16b6-11ea-99b9-523f08ea464e.png)
